#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

$| = 1;

BEGIN {
    # если сайт будет на https
    IO::Socket::SSL::set_ctx_defaults(
        'SSL_verify_mode' => 0 #'SSL_VERIFY_NONE'
    );
    $ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = '0';

    # лимит на объем принимаемых файлов
    $ENV{MOJO_MAX_MEMORY_SIZE} = $ENV{MOJO_MAX_MESSAGE_SIZE} = 2 * 1024 * 1024 * 1024; # 2 GB

    unshift @INC, "$FindBin::Bin/../lib";
}
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('Freee');
