-- CREATE TABLE "public"."EAV_sets" (
--     "eav_id" int4 DEFAULT 0 NOT NULL,
--     "alias" varchar(255) COLLATE "default" NOT NULL,
--     "title" varchar(255) COLLATE "default" NOT NULL,
--     CONSTRAINT "EAV_sets_pkey" PRIMARY KEY ("alias")
-- )
-- WITH (OIDS=FALSE);
